### PR TITLE
Add Zsh completion script

### PR DESCRIPTION
**Pull request by He-Ro**
This is the first Zsh completion script I ever wrote, so it might not be perfect.
Mentioning @filipekiss and @muraii, because they seemed interested in a Zsh completion script. Maybe they can test this one out.

This is how it looks for me after typing `um <TAB>`:
https://ptpb.pw/Apem.png

### CODE REVIEW

**Comment by filipekiss** [comment]
Hey @He-Ro! thanks for tagging me! I'll take a look at it and let you know if I find anything

**Comment by muraii** [comment]
I'll pull this down and test this week. I run with zsh 100% of the time.

**Comment by iajrz** [comment]
Did anyone get around to testing this?

**Comment by sinclairtarget** [comment]
Keep meaning to install zsh and try this out. Should have some time this weekend 🤞

**Comment by sinclairtarget** [comment]
Got around to installing zsh and playing around with this. It works well! Will update the README with information about it once I figure out a good way to make it available once people have installed um

**Pull request merged**
